### ISSUE TITLE
Incompatible API ?

### ISSUE THREAD

**Issue by Sonnenwerk** [poggit-orphanage/essentialsTP#1]
I installed essentialsTP 1.1.1. dev2 (from pogit) for pocketmine dev#210 (API 7)

Following log file entry appeared.

[13:41:09] [Server thread/ERROR]: Could not load plugin 'essentialsTP': Incompatible API version

**Comment by Awzaw** [comment]
For API 3.0.0-ALPHA7 please use the latest build (#7) from https://poggit.pmmp.io/ci/poggit-orphanage/essentialsTP.
