### ISSUE TITLE
Error using "warp" and "home"

### ISSUE THREAD

**Issue by EvoWebFrance** [poggit-orphanage/essentialsTP#12]
Hello,

I can set an home or a warp, but if I want to use /home XXXX or /warp XXXX I have always the error :
**Could not load chunk It's not safe to teleport.**

MineCraft Windows 10 V1.2.8
PocketMine-MP 1.7dev-516 (API 3.0.0-ALPHA10)
EssentialTP Dev Build #24 (poggit)

Any idea ?

**Comment by EvoWebFrance** [comment]
I have an answer :
I had renamed my "world" to "My little word" but in your code, the world name is hard coded to "world" :-)

I had renamed my world to default "world" name and all is working good...

Perhaps you have to retrieve the name off the world before saving home or warp into database !

Regards

**Comment by Awzaw** [comment]
> Perhaps you have to retrieve the name off the world before saving home or warp into database !

Of course the world name is saved for homes and warps... so if you rename a world you'll have to edit the database accordingly. Also, when you edit a world you cannot simply rename the folder, if that is what you did, or you'll mess up lots of plugins: you must also change the contents of level.dat.
